<script setup lang="ts">
import UiSelect from '~/components/ui/UiSelect.vue'
import PaperMapPreview, { type PaperPreviewResult } from '~/components/admin/PaperMapPreview.vue'
import UnsavedChangesGuard from '~/components/admin/UnsavedChangesGuard.vue'
import type { PaperMapConfig, PaperSlotId, PaperTemplateId } from '~~/shared/schemas/paper-map'
import type { PaperMapResponse } from '~~/shared/types/paper-map'
import { paperTemplateCatalog, resolvePaperTemplate, switchPaperTemplate } from '~~/shared/utils/paper-map-templates'

definePageMeta({ layout: 'admin', middleware: 'auth' })
useHead({ title: '紙マップの仕上がり確認' })
const route = useRoute(), mapId = route.params.mapId as string, paperMapId = route.params.paperMapId as string
const { data, status, error } = await useFetch<PaperMapResponse>(`/api/maps/${mapId}/paper-maps/${paperMapId}`)
const name = ref(''), draft = ref<PaperMapConfig | null>(null), savedSnapshot = ref(''), selectedSlot = ref<PaperSlotId | 'title'>('title'), selectedSpotId = ref('')
const previewResult = ref<PaperPreviewResult | null>(null), previewBusy = ref(false)
function previewResolved(result: PaperPreviewResult) { previewResult.value = result; if (data.value && result.source.mode === draft.value?.sourceMode) data.value.source = result.source }
const saving = ref(false), downloading = ref(false), errorMessage = ref(''), advancedOpen = ref(false)
watch(data, (value) => { if (!value) return; name.value = value.paperMap.name; draft.value = structuredClone(value.paperMap.config); savedSnapshot.value = JSON.stringify({ name: name.value, config: draft.value }) }, { immediate: true })
const dirty = computed(() => draft.value ? JSON.stringify({ name: name.value, config: draft.value }) !== savedSnapshot.value : false)
const spots = computed(() => data.value?.source.map.floors.flatMap(floor => floor.spots) ?? [])
watch(spots, (value) => {
  if (!value.some(spot => spot.id === selectedSpotId.value)) selectedSpotId.value = value[0]?.id ?? ''
}, { immediate: true })
const categories = computed(() => [...new Map(spots.value.flatMap(spot => spot.categories).map(category => [category.id, category])).values()])
const template = computed(() => draft.value ? resolvePaperTemplate(draft.value.templateId, draft.value.templateVersion) : null)
const displayWarnings = computed(() => draft.value?.templateVersion === 2 ? previewResult.value?.warnings ?? [] : data.value?.warnings ?? [])
const selectedSpot = computed(() => spots.value.find(spot => spot.id === selectedSpotId.value) ?? spots.value[0])
const currentOverride = computed({ get: () => draft.value?.spotOverrides.find(item => item.spotId === selectedSpot.value?.id)?.summary ?? '', set: (value: string) => { if (!draft.value || !selectedSpot.value) return; draft.value.spotOverrides = draft.value.spotOverrides.filter(item => item.spotId !== selectedSpot.value!.id); if (value.trim()) draft.value.spotOverrides.push({ spotId: selectedSpot.value.id, summary: value }) } })
function toggleId(values: string[], id: string, checked: boolean) { const index = values.indexOf(id); if (checked && index < 0) values.push(id); if (!checked && index >= 0) values.splice(index, 1) }
function selectSlot(slot: PaperSlotId | 'title') { selectedSlot.value = slot }
function changeTemplate(value: string) { if (draft.value) draft.value = switchPaperTemplate(draft.value, value as PaperTemplateId) }
function setSlotVisible(slot: PaperSlotId, visible: boolean) { if (!draft.value) return; draft.value.slotState[slot] = { visible, modified: true } }
function resetSlot() { if (!draft.value) return; const defaults = resolvePaperTemplate(draft.value.templateId, draft.value.templateVersion).slots.find(item => item.id === selectedSlot.value); if (defaults) draft.value.slotState[defaults.id] = { visible: defaults.defaultVisible, modified: false }; if (selectedSlot.value === 'intro') draft.value.paperOriginal.intro = ''; if (selectedSlot.value === 'footer') draft.value.paperOriginal.footer = ''; if (selectedSlot.value === 'qr') draft.value.paperOriginal.qrLabel = '詳しい情報はWebマップで' }
function resetOverride() { currentOverride.value = '' }
function changeViewport(value: string) { if (!draft.value) return; draft.value.viewport = value === 'custom' ? { mode: 'custom', x: .1, y: .1, width: .8, height: .8 } : { mode: value as 'full' | 'fit_spots' } }
function nudgeViewport(dx: number, dy: number, scale = 0) { if (!draft.value || draft.value.viewport.mode !== 'custom') return; const v = draft.value.viewport, width = Math.min(1, Math.max(.2, v.width + scale)), height = Math.min(1, Math.max(.2, v.height + scale)); v.x = Math.min(1 - width, Math.max(0, v.x + dx)); v.y = Math.min(1 - height, Math.max(0, v.y + dy)); v.width = width; v.height = height }
function resetDraft() { if (!data.value) return; name.value = data.value.paperMap.name; draft.value = structuredClone(data.value.paperMap.config) }
async function save() { if (!draft.value) return; saving.value = true; errorMessage.value = ''; try { const response = await $fetch<PaperMapResponse>(`/api/maps/${mapId}/paper-maps/${paperMapId}`, { method: 'PATCH', body: { name: name.value, config: draft.value } }); data.value = response; savedSnapshot.value = JSON.stringify({ name: response.paperMap.name, config: response.paperMap.config }) } catch (cause: any) { errorMessage.value = cause?.data?.statusMessage ?? '保存できませんでした。' } finally { saving.value = false } }
async function downloadPdf() { if (!draft.value) return; downloading.value = true; try { const blob = await $fetch<Blob>(`/api/maps/${mapId}/paper-maps/${paperMapId}/pdf`, { method: 'POST', body: { config: draft.value, previewToken: previewResult.value?.previewToken }, responseType: 'blob' }); const url = URL.createObjectURL(blob); const link = document.createElement('a'); link.href = url; link.download = `${name.value}.pdf`; link.click(); URL.revokeObjectURL(url) } catch (cause: any) { errorMessage.value = cause?.data?.statusMessage ?? 'PDFを作成できませんでした。' } finally { downloading.value = false } }
</script>

<template>
  <div class="max-w-[1500px] pb-24 lg:pb-0"><NuxtLink :to="`/admin/maps/${mapId}/paper`" class="text-sm font-semibold text-stone-600">← 紙マップ一覧</NuxtLink>
    <section v-if="status === 'pending'" class="mt-6 rounded-xl bg-white p-8 text-sm text-stone-600">編集画面を準備しています…</section><section v-else-if="error || !data || !draft" class="mt-6 rounded-xl bg-red-50 p-8 text-sm text-red-700">紙マップを読み込めませんでした。</section>
    <template v-else><header class="top-0 z-30 mt-5 lg:sticky flex flex-wrap items-end justify-between gap-4 bg-stone-50/95 py-3 lg:backdrop-blur"><div><p class="text-sm font-medium text-terracotta-700">紙マップ / 仕上がり確認</p><h1 class="mt-1 text-2xl font-bold">完成品を少し直す</h1><p class="mt-2 text-sm text-stone-600">全ページを確認して、そのままPDFへ。必要な箇所だけ紙専用に調整できます。</p></div><div class="fixed inset-x-0 bottom-0 z-40 flex justify-center gap-2 whitespace-nowrap border-t bg-white p-3 pb-[max(.75rem,env(safe-area-inset-bottom))] lg:static lg:flex-wrap lg:justify-start lg:border-0 lg:bg-transparent lg:p-0"><button type="button" class="min-h-11 rounded-lg px-4 text-sm font-semibold text-stone-700 disabled:opacity-50" :disabled="!dirty || saving" @click="resetDraft">変更を戻す</button><button type="button" class="min-h-11 rounded-lg bg-terracotta-600 px-4 text-sm font-semibold text-white disabled:opacity-40" :disabled="downloading || previewBusy || (draft.templateVersion === 2 && !previewResult?.image)" @click="downloadPdf">{{ downloading ? 'PDF作成中…' : 'PDFをダウンロード' }}</button><button type="button" class="min-h-11 rounded-lg border border-stone-300 bg-white px-5 text-sm font-semibold disabled:opacity-50" :disabled="saving || !dirty" @click="save">{{ saving ? '保存中…' : '保存' }}</button></div></header>

      <div v-if="draft.templateVersion === 1" class="mt-4 rounded-xl bg-sky-50 p-4 text-sm"><p>保存済みの旧版テンプレートを表示しています。新版は読みやすい文字組と全ページの印刷プレビューを使います。</p><button type="button" class="mt-2 min-h-11 rounded-lg border bg-white px-4 font-semibold" @click="changeTemplate(draft.templateId)">内容を引き継いで新版を試す</button></div>
      <p v-if="errorMessage" role="alert" class="mt-4 rounded-lg bg-red-50 p-3 text-sm text-red-700">{{ errorMessage }}</p>
      <div class="mt-6 grid items-start gap-6 lg:grid-cols-[22rem_minmax(0,1fr)]">
        <aside class="space-y-5 rounded-2xl border border-stone-200 bg-white p-5"><div class="mt-4 rounded-xl border border-stone-200 bg-white p-4 text-sm"><span class="font-semibold">元データ：{{ data.source.mode === 'LIVE' ? '現在の編集内容' : '現在の公開版' }}</span><span v-if="data.source.map.releaseId" class="ml-2 text-xs text-stone-500">公開版ID {{ data.source.map.releaseId }}</span><p class="mt-1 text-stone-600">タイトル・紙面用の文章はこの紙マップだけの変更です。Digital Mapの元情報は変わりません。</p><p class="mt-1 text-xs text-stone-500">PDFには現在表示している内容を出力します。設定を残すには「保存」を押してください。</p></div><label class="block text-sm font-semibold">管理用の名前<input v-model="name" maxlength="120" class="dm-field-focus mt-2 min-h-11 w-full rounded-lg border border-stone-300 px-3 font-normal" /></label><label class="block text-sm font-semibold">テンプレート<UiSelect :model-value="draft.templateId" label="テンプレート" class="mt-2" :options="paperTemplateCatalog.map(item => ({ value: item.id, label: item.name }))" @update:model-value="changeTemplate" /></label>
          <div class="flex flex-wrap gap-2" role="group" aria-label="調整する内容"><button v-for="item in [{id:'title',label:'見出し'},{id:'spotGuide',label:'スポット紹介'},{id:'intro',label:'導入文'},{id:'qr',label:'Web案内'},{id:'footer',label:'補足'},{id:'categoryLegend',label:'カテゴリー'},{id:'logo',label:'ロゴ'}]" :key="item.id" type="button" class="min-h-11 rounded-lg border px-3 text-sm" :class="selectedSlot === item.id ? 'border-terracotta-600 bg-terracotta-50' : 'border-stone-200'" :aria-pressed="selectedSlot === item.id" @click="selectSlot(item.id as PaperSlotId | 'title')">{{ item.label }}</button></div>
          <section class="rounded-xl bg-stone-50 p-4"><p class="text-xs font-bold uppercase tracking-wide text-stone-500">紙面だけを調整</p>
            <template v-if="selectedSlot === 'title'"><label class="mt-3 block text-sm font-semibold">タイトル<input v-model="draft.paperOriginal.title" maxlength="120" class="dm-field-focus mt-2 min-h-11 w-full rounded-lg border px-3 font-normal" /></label><label class="mt-3 block text-sm font-semibold">サブタイトル<input v-model="draft.paperOriginal.subtitle" maxlength="240" class="dm-field-focus mt-2 min-h-11 w-full rounded-lg border px-3 font-normal" /></label></template>
            <template v-else-if="selectedSlot === 'intro'"><label class="mt-3 block text-sm font-semibold">導入文<textarea v-model="draft.paperOriginal.intro" maxlength="600" rows="5" class="dm-field-focus mt-2 w-full rounded-lg border p-3 font-normal" /></label></template>
            <template v-else-if="selectedSlot === 'footer'"><label class="mt-3 block text-sm font-semibold">フッター<textarea v-model="draft.paperOriginal.footer" maxlength="240" rows="3" class="dm-field-focus mt-2 w-full rounded-lg border p-3 font-normal" /></label></template>
            <template v-else-if="selectedSlot === 'qr'"><label class="mt-3 block text-sm font-semibold">QRの案内文<input v-model="draft.paperOriginal.qrLabel" maxlength="120" class="dm-field-focus mt-2 min-h-11 w-full rounded-lg border px-3 font-normal" /></label></template>
            <template v-else-if="selectedSlot === 'spotGuide'"><label class="mt-3 block text-sm font-semibold">スポット<UiSelect v-model="selectedSpotId" class="mt-2" label="紙面用の文章を編集するスポット" :options="spots.map(spot => ({ value: spot.id, label: spot.name }))" /></label><p class="mt-3 text-xs text-stone-500">Digital Map由来：{{ selectedSpot?.description || '説明は未設定です' }}</p><label class="mt-3 block text-sm font-semibold">紙面用の短い紹介<textarea v-model="currentOverride" maxlength="400" rows="4" placeholder="未入力なら元の文章を使用" class="dm-field-focus mt-2 w-full rounded-lg border p-3 font-normal" /></label><button type="button" class="mt-2 text-sm font-semibold text-terracotta-700" @click="resetOverride">元の文章に戻す</button><NuxtLink :to="`/admin/maps/${mapId}/spots/${selectedSpot?.id}`" class="mt-2 block text-sm font-semibold text-stone-600">マップ情報を編集 ↗</NuxtLink></template>
            <template v-else><p class="mt-3 text-sm text-stone-600">このブロックは既存マップ情報から自動で作られます。</p></template>
            <div v-if="selectedSlot !== 'title' && template?.slots.some(slot => slot.id === selectedSlot && slot.visibilityEditable)" class="mt-4 flex items-center justify-between border-t pt-3"><span class="text-sm font-semibold">表示</span><button type="button" class="min-h-11 rounded-lg border px-4 text-sm font-semibold" @click="setSlotVisible(selectedSlot as PaperSlotId, !(draft.slotState[selectedSlot as PaperSlotId]?.visible ?? true))">{{ draft.slotState[selectedSlot as PaperSlotId]?.visible ?? true ? '表示しない' : '表示する' }}</button></div><button v-if="selectedSlot !== 'title'" type="button" class="mt-3 text-sm font-semibold text-stone-600" @click="resetSlot">元に戻す</button>
          </section>
          <button type="button" class="w-full rounded-lg border border-stone-300 px-4 py-3 text-left text-sm font-semibold" :aria-expanded="advancedOpen" @click="advancedOpen = !advancedOpen">{{ advancedOpen ? '−' : '+' }} 掲載内容と用紙を調整</button>
          <div v-if="advancedOpen" class="space-y-4 border-l-2 border-stone-200 pl-4"><div class="grid grid-cols-2 gap-2"><label class="text-sm font-semibold">用紙<UiSelect v-model="draft.paper" class="mt-1" label="用紙" :options="[{value:'A4',label:'A4'},{value:'A3',label:'A3'}]" /></label><label class="text-sm font-semibold">向き<UiSelect v-model="draft.orientation" class="mt-1" label="向き" :options="[{value:'portrait',label:'縦'},{value:'landscape',label:'横'}]" /></label></div><label class="block text-sm font-semibold">載せるスポット<UiSelect v-model="draft.selection.mode" class="mt-1" label="載せるスポット" :options="[{value:'recommended',label:'公開スポットすべて'},{value:'categories',label:'カテゴリーで選ぶ'},{value:'spots',label:'スポットを選ぶ'}]" /></label>
            <div v-if="draft.selection.mode === 'categories'" class="max-h-40 space-y-2 overflow-auto rounded-lg bg-stone-50 p-3"><label v-for="category in categories" :key="category.id" class="block text-sm"><input type="checkbox" :checked="draft.selection.categoryIds.includes(category.id)" class="mr-2" @change="toggleId(draft.selection.categoryIds, category.id, ($event.target as HTMLInputElement).checked)">{{ category.name }}</label></div><div v-if="draft.selection.mode === 'spots'" class="max-h-48 space-y-2 overflow-auto rounded-lg bg-stone-50 p-3"><label v-for="spot in spots" :key="spot.id" class="block text-sm"><input type="checkbox" :checked="draft.selection.spotIds.includes(spot.id)" class="mr-2" @change="toggleId(draft.selection.spotIds, spot.id, ($event.target as HTMLInputElement).checked)">{{ spot.name }}</label></div>
            <label class="block text-sm font-semibold">表示範囲<UiSelect :model-value="draft.viewport.mode" class="mt-1" label="表示範囲" :options="[{value:'full',label:'全体'},{value:'fit_spots',label:'掲載スポットに合わせる'},{value:'custom',label:'自分で調整'}]" @update:model-value="changeViewport" /></label><div v-if="draft.viewport.mode === 'custom'" class="rounded-xl border bg-stone-50 p-3"><div class="relative aspect-[4/3] overflow-hidden rounded bg-stone-200"><img :src="data.source.map.floors[0]?.illustrationUrl" alt="表示範囲を調整するマップ" class="size-full object-contain"><div class="absolute border-2 border-sky-500 bg-sky-200/20" :style="{left:`${draft.viewport.x*100}%`,top:`${draft.viewport.y*100}%`,width:`${draft.viewport.width*100}%`,height:`${draft.viewport.height*100}%`}" tabindex="0" aria-label="現在の表示範囲。矢印キーでも移動できます" @keydown.left.prevent="nudgeViewport(-.02,0)" @keydown.right.prevent="nudgeViewport(.02,0)" @keydown.up.prevent="nudgeViewport(0,-.02)" @keydown.down.prevent="nudgeViewport(0,.02)" /></div><div class="mt-2 grid grid-cols-3 gap-1"><span/><button type="button" class="min-h-11 rounded border" aria-label="上へ" @click="nudgeViewport(0,-.03)">↑</button><span/><button type="button" class="min-h-11 rounded border" aria-label="左へ" @click="nudgeViewport(-.03,0)">←</button><button type="button" class="min-h-11 rounded border" aria-label="縮小" @click="nudgeViewport(0,0,.08)">−</button><button type="button" class="min-h-11 rounded border" aria-label="右へ" @click="nudgeViewport(.03,0)">→</button><span/><button type="button" class="min-h-11 rounded border" aria-label="下へ" @click="nudgeViewport(0,.03)">↓</button><button type="button" class="min-h-11 rounded border" aria-label="拡大" @click="nudgeViewport(0,0,-.08)">＋</button></div></div>
            <label class="block text-sm font-semibold">情報量<UiSelect v-model="draft.presentation.informationDensity" class="mt-1" label="情報量" :options="[{value:'names',label:'名前だけ'},{value:'standard',label:'標準'},{value:'detail',label:'詳しく'}]" /></label><label class="block text-sm font-semibold">元データ<UiSelect v-model="draft.sourceMode" class="mt-1" label="元データ" :options="[{value:'LIVE',label:'現在の編集内容'},{value:'PUBLISHED',label:'現在の公開版'}]" /></label>
          </div><NuxtLink :to="`/admin/maps/${mapId}/paper/request?paperMapId=${paperMapId}`" class="block rounded-lg bg-stone-100 px-4 py-3 text-center text-sm font-semibold text-stone-700">デザイン制作を相談する</NuxtLink>
        </aside>
        <div class="order-first min-w-0 lg:sticky lg:top-28 lg:order-last"><PaperMapPreview :map-id="mapId" :config="draft" :source="data.source" :selected-slot="selectedSlot" @slot-select="selectSlot" @resolved="previewResolved" @busy="previewBusy = $event"/><ul v-if="displayWarnings.length" class="mt-4 rounded-lg border border-amber-200 bg-amber-50 p-4 text-sm text-amber-900"><li v-for="warning in displayWarnings" :key="warning">・{{ warning }}</li></ul><p class="mt-2 text-center text-xs text-stone-500">{{ draft.templateVersion === 2 ? 'この紙面はPDFと同じ描画処理で表示しています。' : '旧版の簡易プレビューです。PDFの仕上がりも確認してください。' }}</p></div>
      </div><UnsavedChangesGuard :dirty="dirty && !saving" />
    </template>
  </div>
</template>
