<script setup lang="ts">
definePageMeta({ layout: 'admin', middleware: 'auth' })
const route = useRoute(); const mapId = String(route.params.mapId); const spotId = String(route.params.spotId)
const { data, refresh } = await useFetch(`/api/maps/${mapId}/spots/${spotId}/editor`)
const userId = ref(''); const email = ref(''); const acceptanceUrl = ref(''); const message = ref('')
const { success } = useToast()
async function assign() { await $fetch(`/api/maps/${mapId}/spots/${spotId}/editor`, { method: 'PUT', body: { userId: userId.value } }); success('スポット担当者を設定しました', 'spot-assignee'); await refresh() }
async function remove() { await $fetch(`/api/maps/${mapId}/spots/${spotId}/editor`, { method: 'DELETE' }); success('スポット担当者を解除しました', 'spot-assignee'); await refresh() }
async function invite() { const result = await $fetch(`/api/maps/${mapId}/spots/${spotId}/editor/invite`, { method: 'POST', body: { email: email.value } }); acceptanceUrl.value = result.acceptanceUrl ?? ''; if (result.delivery.status === 'SENT') success('スポット担当者招待を送信しました', 'spot-assignee'); else message.value = '招待を作成しましたが、メール配信設定を確認してください。' }
</script>
<template><section class="max-w-2xl"><NuxtLink :to="`/admin/maps/${mapId}/spots/${spotId}`" class="text-sm underline">← スポット編集へ</NuxtLink><h1 class="mt-5 text-2xl font-bold">スポット担当者</h1><p v-if="message" class="mt-4 rounded bg-amber-50 p-3">{{ message }}</p><div class="mt-6 rounded-xl bg-white p-6"><p>現在: {{ data?.assignment?.user.displayName || data?.assignment?.user.email || '未設定' }}</p><form class="mt-4 flex gap-2" @submit.prevent="assign"><UiSelect v-model="userId" class="flex-1" label="同じワークスペースのメンバー" :options="(data?.members ?? []).map(member => ({ value: member.userId, label: member.displayName || member.email }))" /><button class="rounded bg-stone-900 px-4 text-white">設定</button></form><button v-if="data?.assignment" class="mt-3 text-sm text-red-700" @click="remove">担当解除</button></div><div class="mt-6 rounded-xl bg-white p-6"><h2 class="font-bold">新規ユーザーを招待（オーナーのみ）</h2><form class="mt-3 flex gap-2" @submit.prevent="invite"><input v-model="email" required type="email" class="flex-1 rounded border px-3 py-2"><button class="rounded bg-terracotta-600 px-4 text-white">招待</button></form><input v-if="acceptanceUrl" readonly :value="acceptanceUrl" class="mt-3 w-full rounded border px-2 py-1 text-xs"></div></section></template>
